### ISSUE TITLE
Cuda problems

### ISSUE THREAD

**Issue by adelsonvelskylandis** [christian-smith/cruzbit#1]
Works without CUDA, when I try to use CUDA it fails

$ cmake --version
cmake version 3.27.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).

$ gcc --version
gcc (Ubuntu 13.2.0-4ubuntu3) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.

$ rustc --version
rustc 1.71.1 (eb26296b5 2023-08-03) (built from a source tarball)

$ cargo run --release --features cuda -- --datadir clientdata --numminers 1 --keyfile keys.txt
[?2004l
[0m[0m[1m[32m   Compiling[0m cruzbit v1.0.0 (/home/cruz/dev/git/cruzbit)
[0m[0m[1m[36m    Building[0m [=======================> ] 224/227: cruzbit(build)                                                                        
[K[0m[0m[1m[31merror[0m[1m:[0m failed to run custom build command for `cruzbit v1.0.0 (/home/cruz/dev/git/cruzbit)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/home/cruz/dev/git/cruzbit/target/release/build/cruzbit-1465cdb51d43fdea/build-script-build` (exit status: 101)
  --- stdout
  CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-unknown-linux-gnu = None
  CMAKE_GENERATOR_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-unknown-linux-gnu = None
  CMAKE_PREFIX_PATH_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-unknown-linux-gnu = None
  CMAKE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE = None
  CMAKE = None
  running: cd "/home/cruz/dev/git/cruzbit/target/release/build/cruzbit-2bd5222d5d18c889/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/home/cruz/dev/git/cruzbit/src/cuda" "-DCMAKE_INSTALL_LIBDIR=/home/cruz/dev/git/cruzbit/target/release/build/cruzbit-2bd5222d5d18c889/out/lib" "-DCMAKE_INSTALL_PREFIX=/home/cruz/dev/git/cruzbit/target/release/build/cruzbit-2bd5222d5d18c889/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Release"
  -- Configuring done (0.0s)
  -- Generating done (0.0s)
  -- Build files have been written to: /home/cruz/dev/git/cruzbit/target/release/build/cruzbit-2bd5222d5d18c889/out/build
  running: cd "/home/cruz/dev/git/cruzbit/target/release/build/cruzbit-2bd5222d5d18c889/out/build" && MAKEFLAGS="-j --jobserver-fds=7,8 --jobserver-auth=7,8" "cmake" "--build" "." "--target" "install" "--config" "Release"
  [ 40%] Building NVCC (Device) object CMakeFiles/cruzbit_cuda.dir/cruzbit_cuda_generated_mine.cu.o
  [ 40%] Building NVCC (Device) object CMakeFiles/cruzbit_cuda.dir/cruzbit_cuda_generated_sha3.cu.o

  --- stderr
  CMake Warning (dev) at CMakeLists.txt:3 (find_package):
    Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
    --help-policy CMP0146" for policy details.  Use the cmake_policy command to
    set the policy and suppress this warning.

  This warning is for project developers.  Use -Wno-dev to suppress it.

  In file included from /usr/include/cuda_runtime.h:83,
                   from <command-line>:
  /usr/include/crt/host_config.h:132:2: error: #error -- unsupported GNU version! gcc versions later than 12 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
    132 | #error -- unsupported GNU version! gcc versions later than 12 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
        |  ^~~~~
  In file included from /usr/include/cuda_runtime.h:83,
                   from <command-line>:
  /usr/include/crt/host_config.h:132:2: error: #error -- unsupported GNU version! gcc versions later than 12 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
    132 | #error -- unsupported GNU version! gcc versions later than 12 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
        |  ^~~~~
  CMake Error at cruzbit_cuda_generated_sha3.cu.o.Release.cmake:220 (message):
    Error generating
    /home/cruz/dev/git/cruzbit/target/release/build/cruzbit-2bd5222d5d18c889/out/build/CMakeFiles/cruzbit_cuda.dir//./cruzbit_cuda_generated_sha3.cu.o

  gmake[2]: *** [CMakeFiles/cruzbit_cuda.dir/build.make:84: CMakeFiles/cruzbit_cuda.dir/cruzbit_cuda_generated_sha3.cu.o] Error 1
  gmake[2]: *** Waiting for unfinished jobs....
  CMake Error at cruzbit_cuda_generated_mine.cu.o.Release.cmake:220 (message):
    Error generating
    /home/cruz/dev/git/cruzbit/target/release/build/cruzbit-2bd5222d5d18c889/out/build/CMakeFiles/cruzbit_cuda.dir//./cruzbit_cuda_generated_mine.cu.o

  gmake[2]: *** [CMakeFiles/cruzbit_cuda.dir/build.make:77: CMakeFiles/cruzbit_cuda.dir/cruzbit_cuda_generated_mine.cu.o] Error 1
  gmake[1]: *** [CMakeFiles/Makefile2:82: CMakeFiles/cruzbit_cuda.dir/all] Error 2
  gmake: *** [Makefile:136: all] Error 2
  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 2

  build script failed, must exit now', /home/cruz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5
  stack backtrace:
     0:     0x5650dd32ba70 - std::backtrace_rs::backtrace::libunwind::trace::h5504888a16f015a0
                                 at /build/rustc-6BaN2t/rustc-1.71.1+dfsg0ubuntu2/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0x5650dd32ba70 - std::backtrace_rs::backtrace::trace_unsynchronized::h76fb636b288f7c51
                                 at /build/rustc-6BaN2t/rustc-1.71.1+dfsg0ubuntu2/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x5650dd32ba70 - std::sys_common::backtrace::_print_fmt::h86d056415a534e22
                                 at /build/rustc-6BaN2t/rustc-1.71.1+dfsg0ubuntu2/library/std/src/sys_common/backtrace.rs:65:5
     3:     0x5650dd32ba70 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hcb0152b2389513a4
                                 at /build/rustc-6BaN2t/rustc-1.71.1+dfsg0ubuntu2/library/std/src/sys_common/backtrace.rs:44:22
     4:     0x5650dd370b2f - core::fmt::rt::Argument::fmt::hb5253add6afe3bbe
                                 at /build/rustc-6BaN2t/rustc-1.71.1+dfsg0ubuntu2/library/core/src/fmt/rt.rs:138:9
     5:     0x5650dd370b2f - core::fmt::write::h5534942d24bcba94
                                 at /build/rustc-6BaN2t/rustc-1.71.1+dfsg0ubuntu2/library/core/src/fmt/mod.rs:1094:21
     6:     0x5650dd3379d1 - std::io::Write::write_fmt::h01ef66d7c428f294
                                 at /build/rustc-6BaN2t/rustc-1.71.1+dfsg0ubuntu2/library/std/src/io/mod.rs:1713:15
     7:     0x5650dd32b875 - std::sys_common::backtrace::_print::hcec173636e6727b1
                                 at /build/rustc-6BaN2t/rustc-1.71.1+dfsg0ubuntu2/library/std/src/sys_common/backtrace.rs:47:5
     8:     0x5650dd32b875 - std::sys_common::backtrace::print::hd6be3868713f50ea
                                 at /build/rustc-6BaN2t/rustc-1.71.1+dfsg0ubuntu2/library/std/src/sys_common/backtrace.rs:34:9
     9:     0x5650dd342747 - std::panicking::default_hook::{{closure}}::he8b2712aefc606f7
    10:     0x5650dd3424b2 - std::panicking::default_hook::h12d66989012e06d1
                                 at /build/rustc-6BaN2t/rustc-1.71.1+dfsg0ubuntu2/library/std/src/panicking.rs:288:9
    11:     0x5650dd342b1c - std::panicking::rust_panic_with_hook::h51178b6a1900429f
                                 at /build/rustc-6BaN2t/rustc-1.71.1+dfsg0ubuntu2/library/std/src/panicking.rs:705:13
    12:     0x5650dd32bd57 - std::panicking::begin_panic_handler::{{closure}}::haa306818c2a33bd2
                                 at /build/rustc-6BaN2t/rustc-1.71.1+dfsg0ubuntu2/library/std/src/panicking.rs:597:13
    13:     0x5650dd32bb46 - std::sys_common::backtrace::__rust_end_short_backtrace::h88ee2ece90b9f26f
                                 at /build/rustc-6BaN2t/rustc-1.71.1+dfsg0ubuntu2/library/std/src/sys_common/backtrace.rs:151:18
    14:     0x5650dd342842 - rust_begin_unwind
                                 at /build/rustc-6BaN2t/rustc-1.71.1+dfsg0ubuntu2/library/std/src/panicking.rs:593:5
    15:     0x5650dd2cdaf3 - core::panicking::panic_fmt::hc5a8d1a52e3b73ac
                                 at /build/rustc-6BaN2t/rustc-1.71.1+dfsg0ubuntu2/library/core/src/panicking.rs:67:14
    16:     0x5650dd2d8d31 - cmake::fail::h109902dae52749a6
    17:     0x5650dd2d8828 - cmake::run::h1701d0db97efc5c5
    18:     0x5650dd2d51c0 - cmake::Config::build::h87e1557e1cbcf891
    19:     0x5650dd2ce2b8 - build_script_build::main::hb9529091dc157e4b
    20:     0x5650dd2cf053 - core::ops::function::FnOnce::call_once::h40f484a055ac4392
    21:     0x5650dd2cea36 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd60f85539f901e61
    22:     0x5650dd2ce6a9 - std::rt::lang_start::{{closure}}::hc4b1c408d7af170f
    23:     0x5650dd357337 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h75cf23ad5ca7409a
                                 at /build/rustc-6BaN2t/rustc-1.71.1+dfsg0ubuntu2/library/core/src/ops/function.rs:284:13
    24:     0x5650dd357337 - std::panicking::try::do_call::hb170c4049adb1a96
                                 at /build/rustc-6BaN2t/rustc-1.71.1+dfsg0ubuntu2/library/std/src/panicking.rs:500:40
    25:     0x5650dd357337 - std::panicking::try::h925497fe0cf0c566
                                 at /build/rustc-6BaN2t/rustc-1.71.1+dfsg0ubuntu2/library/std/src/panicking.rs:464:19
    26:     0x5650dd357337 - std::panic::catch_unwind::h86baecbf258bb08f
                                 at /build/rustc-6BaN2t/rustc-1.71.1+dfsg0ubuntu2/library/std/src/panic.rs:142:14
    27:     0x5650dd357337 - std::rt::lang_start_internal::{{closure}}::h1b01213c1624d317
                                 at /build/rustc-6BaN2t/rustc-1.71.1+dfsg0ubuntu2/library/std/src/rt.rs:148:48
    28:     0x5650dd357337 - std::panicking::try::do_call::hf88c5e48d4b8c12e
                                 at /build/rustc-6BaN2t/rustc-1.71.1+dfsg0ubuntu2/library/std/src/panicking.rs:500:40
    29:     0x5650dd357337 - std::panicking::try::h513fb335101aeca1
                                 at /build/rustc-6BaN2t/rustc-1.71.1+dfsg0ubuntu2/library/std/src/panicking.rs:464:19
    30:     0x5650dd357337 - std::panic::catch_unwind::h3ac22b29534268f4
                                 at /build/rustc-6BaN2t/rustc-1.71.1+dfsg0ubuntu2/library/std/src/panic.rs:142:14
    31:     0x5650dd357337 - std::rt::lang_start_internal::hf0ad87b2bc1980b1
                                 at /build/rustc-6BaN2t/rustc-1.71.1+dfsg0ubuntu2/library/std/src/rt.rs:148:20
    32:     0x5650dd2ce687 - std::rt::lang_start::hb15567eae4d57813
    33:     0x5650dd2ce5f5 - main
    34:     0x7f42fd2280d0 - __libc_start_call_main
                                 at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    35:     0x7f42fd228189 - __libc_start_main_impl
                                 at ./csu/../csu/libc-start.c:360:3
    36:     0x5650dd2cde85 - _start
    37:                0x0 - <unknown>
[?2004h]0;cruz@system76-pc: ~/dev/git/cruzbit

**Comment by christian-smith** [comment]
It looks like your version of gcc (v12) is not supported by CUDA (nvcc). Can you install gcc v11? I have an Ubuntu system with gcc 11.4 installed and it's compiling/running without any issues.
